local Loc = LibStub("AceLocale-3.0"):NewLocale("Details_EncounterDetails", "ptBR") 

if (not Loc) then
	return 
end 

Loc["STRING_PLUGIN_NAME"] = "Details do Combate"
Loc["STRING_WINDOW_TITLE"] = "Details do Combate"
Loc["STRING_TOTAL_DAMAGE"] = "Total de Dano"
Loc["STRING_TOTAL_HEAL"] = "Total de Cura"
Loc["STRING_SHOW_ALL_DATA"] = "Mostrar dados totais"
Loc["STRING_SHOW_PHASE_DATA"] = "Mostrar dados apenas para this fase"
Loc["STRING_NOT IMPLEMENTED"] = "Not this implementado ainda"
Loc["STRING_DIED"] = "morreu"
Loc["STRING_MELEE_DAMAGE"] = "damage corpo-a-corpo"
Loc["STRING_DAMAGE_TAKEN_REPORT"] = "Dano received por ability"
Loc["STRING_ABILITY_DAMAGE"] = "Dano da ability"
Loc["STRING_DAMAGE_TAKEN"] = "Dano received"
Loc["STRING_TOOK_DAMAGE_FROM"] = "Recebeu damage de"
Loc["STRING_INTERRUPT_BY"] = "interrompido por"
Loc["STRING_DISPELLED_BY"] = "removido por"
Loc["STRING_DEAD_LOG"] = "ultimos seconds de"
Loc["STRING_CURRENT"] = "Atual"
Loc["STRING_TRY"] = "Luta"
Loc["STRING_DAMAGE_AT"] = "Dano causado em"
Loc["STRING_INFLICTED_BY"] = "Dano causado por"
Loc["STRING_ADDS"] = "Adds"
Loc["STRING_INTERRUPTS"] = "Cortes"
Loc["STRING_DISPELLS"] = "Dissipados"
Loc["STRING_DEATH_LOG"] = "Ultimos Segundos"
Loc["STRING_FIGHT_SUMMARY"] = "details da fight"
Loc["STRING_FIGHT_GRAPHIC"] = "graficos da performance"
Loc["STRING_TOOLTIP"] = "Mostrar os details do combat"
Loc["STRING_LAST_COOLDOWN"] = "ultimo cooldown usado"
Loc["STRING_NOLAST_COOLDOWN"] = "nenhum cooldown usado"

Loc["STRING_HOLDSHIFT"] = "SHIFT Para Descricao da Spell"

Loc["STRING_ADDS_HELP"] = "Passe o mouse |cFF00FF00Flecha|r\ndamage received, |cFFFF0000Flecha|r\ndamage feito.|cFFFFFF00Clique|r: Reporta\nos dados no tooltip."
Loc["STRING_INTERRIPT_HELP"] = "\n\n|cFFFFFF00Clique|r na bar: open a window de sendr report."
Loc["STRING_DISPELL_HELP"] = "\n\n|cFFFFFF00Clique|r na bar: open a window de sendr report."
Loc["STRING_DEATHS_HELP"] = "\n\n|cFFFFFF00Clique|r na bar: open a window de sendr report."

--> mechanic types
Loc["STRING_HEAL"] = "heal"
Loc["STRING_LOWDPS"] = "dpsbaixo"
Loc["STRING_LOWHEAL"] = "healbaixa"
Loc["STRING_VOIDZONE"] = "voidzone"
Loc["STRING_DISPELL"] = "dispell"
Loc["STRING_INTERRUPT"] = "interromper"
Loc["STRING_POSITIONING"] = "position"
Loc["STRING_RUNAWAY"] = "correr"
Loc["STRING_TANKSWITCH"] = "trocadetank"
Loc["STRING_MECHANIC"] = "mecanica"
Loc["STRING_CROWDCONTROL"] = "cc"
Loc["STRING_TANKCOOLDOWN"] = "tankcooldown"
Loc["STRING_KILLADD"] = "mataradd"
Loc["STRING_SPREADOUT"] = "separar"
Loc["STRING_STOPCAST"] = "pararcast"
Loc["STRING_FACING"] = "virar"
Loc["STRING_STACK"] = "juntar"